#!/bin/env Rscript

# FULL DISCLOSURE: MOSTLY GENERATED BY CHATGPT

library(ggplot2)
library(tidyverse)

# Load CSV
exp2base <- read.csv("csvs/experiment2-baseline.csv") %>% mutate(source = "Baseline")
exp2vect <- read.csv("csvs/experiment2-vectorized.csv") %>% mutate(source = "Vectorized")

# Define X positions for vertical lines
vlines <- c(30038, 567979, 1048577)

# Combine into one dataframe
exp2 <- bind_rows(exp2base, exp2vect)

ggplot(exp2, aes(x = length, y = avg_time_ns, color = source, fill = source)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = min_time_ns, ymax = max_time_ns), alpha = 0.2, color = NA) +
  geom_vline(xintercept = vlines, linetype = "dashed", color = "darkgrey") +
  labs(title = "Experiment 2 Performance (time)",
       x = "Array Length",
       y = "Time (ns)") +
  scale_color_manual(values = c("blue", "red")) +
  scale_fill_manual(values = c("blue", "red")) +
  theme_classic()

ggplot(exp2, aes(x = length, y = avg_cycles / length, color = source, fill = source)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = min_cycles / length, ymax = max_cycles / length), alpha = 0.2, color = NA) +
  geom_vline(xintercept = vlines, linetype = "dashed", color = "darkgrey") +
  labs(title = "Experiment 2 Performance (CPE)",
       x = "Array Length",
       y = "Cycles") +
  scale_color_manual(values = c("blue", "red")) +
  scale_fill_manual(values = c("blue", "red")) +
  theme_classic()
